# Configuration file for Embedding Generation Service

# Kafka Configuration
kafka:
  bootstrap_servers: "kafka:29092"
  input_topic: "text-messages"
  output_topic: "embeddings"
  consumer_group: "embedding-service"
  auto_offset_reset: "latest"
  enable_auto_commit: true

# Hugging Face Model Configuration
model:
  name: "sentence-transformers/all-MiniLM-L6-v2"
  max_length: 512
  device: "cpu"  # Use "cuda" if GPU is available

# Flask Configuration
flask:
  host: "0.0.0.0"
  port: 5000
  debug: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Service Configuration
service:
  name: "embedding-generation-service"
  version: "1.0.0"
  health_check_interval: 30  # seconds
