kafka:
  bootstrap_servers: "kafka:29092"
  topic: "embeddings"
  group_id: "writer-service"

database:
  type: "lancedb"  # Options: "lancedb", "postgres"
  
  lancedb:
    data_path: "./lancedb_data"
    
  postgres:
    host: "postgres"
    port: 5432
    database: "embeddings_db"
    user: "postgres"
    password: "postgres"
