kafka:
  bootstrap_servers: "kafka:29092"
  topic: "embeddings"
  group_id: "writer-service"

database:
  type: "postgres"
  
  postgres:
    host: "postgres"
    port: 5432
    database: "embeddings_db"
    user: "postgres"
    password: "postgres"
