# Writer Service Configuration

# Kafka Configuration
kafka:
  bootstrap_servers: "kafka:29092"
  input_topic: "embeddings"
  consumer_group: "writer-service"

# Database Configuration
# Choose one database type: 'lancedb' or 'postgres'
database:
  type: "lancedb"  # Options: lancedb, postgres
  
  # LanceDB Configuration
  lancedb:
    table_name: "embeddings"
    db_path: "./lancedb_data"
  
  # PostgreSQL Configuration
  postgres:
    host: "postgres"
    port: 5432
    database: "embeddings_db"
    user: "postgres"
    password: "postgres"
    table_name: "embeddings"

# Flask Configuration
flask:
  host: "0.0.0.0"
  port: 5001
  debug: false

# Logging Configuration
logging:
  level: "INFO"
  file: "writer_service.log"
