services:
  writer-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: writer-service
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_TYPE=${DATABASE_TYPE:-lancedb}
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - writer-logs:/app/logs
      - lancedb-data:/app/lancedb_data
    networks:
      - kafka-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  writer-logs:
    driver: local
  lancedb-data:
    driver: local

networks:
  kafka-network:
    external: true
