version: '3.8'

services:
  writer-service:
    build: 
      context: .
      network: host
    ports:
      - "5001:5000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - FLASK_ENV=production
    networks:
      - kafka-network
    depends_on:
      - kafka
    restart: unless-stopped

networks:
  kafka-network:
    external: true
