version: '3.8'

services:
  writer-service:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./lancedb_data:/app/lancedb_data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - FLASK_ENV=production
    networks:
      - kafka-network
    depends_on:
      - kafka
    restart: unless-stopped

networks:
  kafka-network:
    external: true
