# Centralized Docker Compose for Real-time LLM Ingestion Architecture
# Imports configurations from individual service directories

# Import configurations from other directories
services:
  # Kafka infrastructure (imported from kafka directory)
  zookeeper:
    extends:
      file: ../kafka/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: ../kafka/docker-compose.yml
      service: kafka

  kafka-ui:
    extends:
      file: ../kafka/docker-compose.yml
      service: kafka-ui

  schema-registry:
    extends:
      file: ../kafka/docker-compose.yml
      service: schema-registry

  kafka-connect:
    extends:
      file: ../kafka/docker-compose.yml
      service: kafka-connect

  # Embedding service (imported from embedding_gen_svc directory)
  embedding-service:
    extends:
      file: ../embedding_gen_svc/docker-compose.yml
      service: embedding-service
    depends_on:
      - kafka
      - schema-registry

  # Writer service (imported from writer_svc directory)
  writer-service:
    extends:
      file: ../writer_svc/docker-compose.yml
      service: writer-service
    depends_on:
      - kafka
      - embedding-service
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE:-lancedb}

  # Database services (conditional based on DATABASE_TYPE)
  postgres:
    extends:
      file: ../pgvector/docker-compose.yml
      service: postgres
    depends_on:
      - kafka
    profiles:
      - postgres

  pgadmin:
    extends:
      file: ../pgvector/docker-compose.yml
      service: pgadmin
    depends_on:
      - postgres
    profiles:
      - postgres

  lancedb-env:
    extends:
      file: ../lancedb/docker-compose.yml
      service: lancedb-env
    depends_on:
      - kafka
    profiles:
      - lancedb
    volumes:
      - lancedb-data:/data
      - ../lancedb:/app

# Import all volumes from other compose files
volumes:
  # Kafka volumes
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local
  
  # Embedding service volumes
  embedding-logs:
    driver: local
  
  # Writer service volumes
  writer-logs:
    driver: local
  lancedb-data:
    driver: local
  
  # PostgreSQL volumes
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

# Import all networks from other compose files
networks:
  kafka-network:
    driver: bridge
  pgvector-network:
    driver: bridge
  lancedb-network:
    driver: bridge
