# Centralized Docker Compose for Real-time LLM Ingestion Architecture
# Imports configurations from individual service directories

# Import configurations from other directories
services:
  # Kafka infrastructure (imported from kafka directory)
  zookeeper:
    extends:
      file: ../kafka/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: ../kafka/docker-compose.yml
      service: kafka

  kafka-ui:
    extends:
      file: ../kafka/docker-compose.yml
      service: kafka-ui

  schema-registry:
    extends:
      file: ../kafka/docker-compose.yml
      service: schema-registry

  kafka-connect:
    extends:
      file: ../kafka/docker-compose.yml
      service: kafka-connect

  # Embedding service (imported from embedding_gen_svc directory)
  embedding-service:
    extends:
      file: ../embedding_gen_svc/docker-compose.yml
      service: embedding-service
    depends_on:
      - kafka
      - schema-registry

  


# Import all volumes from other compose files
volumes:
  # Kafka volumes
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local
  
  # Embedding service volumes
  embedding-logs:
    driver: local

# Define networks
networks:
  kafka-network:
    name: kafka-network
    driver: bridge
